vim.g.mapleader        = '\\'
vim.opt.mouse          = 'a'
vim.opt.autoindent     = true
vim.opt.expandtab      = true
vim.opt.tabstop        = 4
vim.opt.shiftwidth     = 4
vim.opt.softtabstop    = 4
vim.opt.swapfile       = false
-- vim.opt.background     = 'dark'
vim.opt.backup         = false
vim.opt.clipboard      = 'unnamedplus'
vim.opt.completeopt    = 'menu,menuone,noselect'
vim.opt.hidden         = true
vim.opt.hlsearch       = true
vim.opt.shiftround     = true
vim.opt.termguicolors  = true
vim.opt.updatetime     = 0
vim.opt.wildmenu       = true
vim.opt.wildmode       = 'longest:full,full'
vim.opt.writebackup    = false
vim.opt.splitright     = true
vim.opt.splitbelow     = true
vim.opt.conceallevel   = 2
vim.opt.cursorline     = true
vim.opt.list           = true
vim.opt.fillchars      = 'fold: '
vim.opt.number         = true
vim.opt.relativenumber = true
vim.opt.signcolumn     = 'yes'
vim.opt.spell          = false
vim.opt.wrap           = false
vim.opt.foldmethod     = 'expr'
vim.opt.foldexpr       = 'nvim_treesitter#foldexpr()'
vim.opt.pumheight      = 20
vim.opt.shortmess:append('c')
